repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.357
    hooks:
      - id: pyright
        additional_dependencies:
          [beartype, jax, jaxtyping, pytest, typing_extensions]
